[project]
name = "novake"
version = "0.1.0"
description = "AI-powered training buddy and mentor"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-ollama>=0.2.3",
    "langchain-openai>=0.3.8",
    "langgraph>=0.3.5",
]
